services:
  stats-server:
    build: ./stats-service/server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build: ./main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      ewm-db:
        condition: service_healthy

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10